# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('institution', models.CharField(max_length=128)),
                ('course_url', models.URLField()),
                ('materials_url', models.URLField(blank=True)),
                ('end_date', models.DateField()),
                ('pic1', models.ImageField(upload_to=b'courses_images')),
                ('pic2', models.ImageField(upload_to=b'courses_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('company_url', models.URLField()),
                ('location', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pic1', models.ImageField(upload_to=b'job_images')),
                ('pic2', models.ImageField(upload_to=b'job_images')),
                ('pic3', models.ImageField(upload_to=b'job_images')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('pic1', models.ImageField(upload_to=b'projects_images')),
                ('video_url', models.URLField(blank=True)),
            ],
        ),
    ]
